// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: hello.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SayHi_SayHi_FullMethodName = "/SayHi/SayHi"
)

// SayHiClient is the client API for SayHi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayHiClient interface {
	SayHi(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type sayHiClient struct {
	cc grpc.ClientConnInterface
}

func NewSayHiClient(cc grpc.ClientConnInterface) SayHiClient {
	return &sayHiClient{cc}
}

func (c *sayHiClient) SayHi(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, SayHi_SayHi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayHiServer is the server API for SayHi service.
// All implementations must embed UnimplementedSayHiServer
// for forward compatibility.
type SayHiServer interface {
	SayHi(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedSayHiServer()
}

// UnimplementedSayHiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSayHiServer struct{}

func (UnimplementedSayHiServer) SayHi(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedSayHiServer) mustEmbedUnimplementedSayHiServer() {}
func (UnimplementedSayHiServer) testEmbeddedByValue()               {}

// UnsafeSayHiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayHiServer will
// result in compilation errors.
type UnsafeSayHiServer interface {
	mustEmbedUnimplementedSayHiServer()
}

func RegisterSayHiServer(s grpc.ServiceRegistrar, srv SayHiServer) {
	// If the following call pancis, it indicates UnimplementedSayHiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SayHi_ServiceDesc, srv)
}

func _SayHi_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayHiServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SayHi_SayHi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayHiServer).SayHi(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SayHi_ServiceDesc is the grpc.ServiceDesc for SayHi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SayHi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SayHi",
	HandlerType: (*SayHiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _SayHi_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
